[target.nanos]
runner = "speculos -m nanos --display=headless"

[target.nanox]
runner = "speculos -m nanox --display=headless"

[target.nanosplus]
runner = "speculos -m nanosp --display=headless"

[target.stax]
runner = "speculos --model stax --display=headless"

[target.flex]
runner = "speculos --model flex --display=headless"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "stax"
