[target.nanos]
runner = "speculos -m nanos --display=headless"

[target.nanox]
runner = "speculos -m nanox --display=headless"

[target.nanosplus]
runner = "speculos -m nanosp --display=headless"

[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "nanosplus"
