[target.nanox]
runner = "speculos -m nanox --display=headless --api-port 5001"

[target.nanosplus]
runner = "speculos -m nanosp --display=headless --api-port 5001"

[target.stax]
runner = "speculos --model stax"

[target.flex]
runner = "speculos --model flex"

[target.apex_p]
runner = "speculos --model apex_p"